### ISSUE TITLE
crash guild bank !

### ISSUE THREAD

**Issue by Motorheadx** [callmephil/SunWellCore#12] opened 2016-03-11 11:08 UTC
When I spread the rags in the guild bank server crashes, ask for fixes =)

**Comment by callmephil** [comment] 2016-03-11 12:07
any crash logs ?

**Comment by Motorheadx** [comment] 2016-03-11 12:51
no crash log, the server just shut down

**Comment by Devalenok** [comment] 2016-03-11 23:27
That's for sure

**Comment by callmephil** [comment] 2016-03-15 04:09
Why did you close the issue @Motorheadx  ? my pc took the water so i'm currently using my old one but it takes a lot of time to setup everything back etc.

**Comment by ghost** [comment] 2016-03-15 20:07
cannot reproduce the crash, provide more information please.
maybe caused after injecting the update which is supposed to allow GM lvl accounts to access the guild bank? (using the sunwell repack from ac-web, not compiled self yet on windows, on linux working)

**Comment by callmephil** [comment] 2016-03-15 20:26
Repack isn't yet updated my laptop got water inside. the crash occur when you deposit an item in the guild bank. and refer to https://github.com/callmephil/SunWellCore/commit/73b4fb43973583401d198a43658c37015f74f963

**Closed as completed** 2016-03-15 21:55 UTC
